### PR TITLE
feat: added typography component

### PR DESCRIPTION
**Pull request by SanjayJatti**
- Headings from h1 to h5
- Types of paragraph text
- Some extra style
Typoghphy component
s

### CODE REVIEW

**Review by Omkar-Ghate — COMMENTED** [review]
Looks great!. Neat and clean UI.

**Review by shivanigangadharan — APPROVED** [review]
Very clean code, with comments too. Looks good to merge. 👍

**Comment by SanjayJatti** [comment]
> Very clean code, with comments too. Looks good to merge. 👍

Thank you Shivani!

**Comment by SanjayJatti** [comment]
> Looks great!. Neat and clean UI.

Thank you Omkar!

**Pull request merged**
