### PR TITLE
feat: added card component

### PR DESCRIPTION
**Pull request by SanjayJatti**
- Vertical card
- Card with badge
- Card with text overlays
- Card with dismiss
- Horizontal card
- Text only card
Card-component

### CODE REVIEW

**Review by ashishnnnnn — APPROVED** [review]
Code Seems Fine.. and preview also looks good..
Good to merge :+1:

**Comment by SanjayJatti** [comment]
> Code Seems Fine.. and preview also looks good.. Good to merge 👍

Thank you Ashish!

**Review by ishapatell1 — APPROVED** [review]
Small Changes in padding and font size are making the UI look good. Code is good enough to merge sanjay.

**Comment by SanjayJatti** [comment]
> Small Changes in padding and font size are making the UI look good. Code is good enough to merge sanjay.

Thank you Isha!

**Pull request merged**
